blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
	# /blog/ 
    url(r'^$', views.index, name='index'),
    # /blog/{blog_id}
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='detail'),
    # /blog/{blog_id}/favorite/
    url(r'^(?P<blog_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

webproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length = 255)
	album_title = models.CharField(max_length = 255)
	genre = models.CharField(max_length = 255)
	album_logo = models.CharField(max_length = 255)

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	file_type = models.CharField(max_length = 255)
	song_title = models.CharField(max_length = 255)
	is_favorite = models.BooleanField(default = False)

	def __str__(self):
		return self.song_title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

# Create your views here.
def index(request):
	all_albums = Album.objects.all()
	return render(request, 'blog/index.html', {'all_albums' : all_albums})

def detail(request, blog_id):
	album = get_object_or_404(Album, pk = blog_id)
	return render(request, 'blog/detail.html', {'album' : album})

def favorite(request, blog_id):
	album = get_object_or_404(Album, pk = blog_id)
	try:
		selected_song = album.song_set.get(pk = request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'blog/detail.html', {
			'album' : album,
			'error_message' : "You did not select a valid song",
			})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return render(request, 'blog/detail.html', {'album' : album})

blog/templates/blog/detail.html
<img src="{{album.album_logo}}">

<h1> {{album_title}} </h1>
<h3> {{album.artist}} </h3>

{% if error_message %}
	<p> <strong> {{error_message}} </strong> </p>
{% endif %}

<form action="{% url 'blog:favorite' album.id %}" method="post">
	{% csrf_token %}
		{% for song in album.song_set.all %}
			<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
			<label for="song{{ forloop.counter }}">
				{{ song.song_title }}
				{% if song.is_favorite %}
					<img src="http://i.imgur.com/b9b13Rd.png" />
				{% endif %}
			</label> <br>
		{% endfor %}
	<input type="submit" value="Favorite">
</form>

blog/templates/blog/index.html
<!-- load static files -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet"> 
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<nav class="navbar navbar-inverse"> 
	<div class="container-fluid">
		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"> </span>
				<span class="icon-bar"> </span>
				<span class="icon-bar"> </span>
			</button>
			<a class="navbar-brand" href="{% url 'blog:index'%}">BLOG</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse"> 
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'blog:index'%}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span> &nbsp; Albums
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span> &nbsp; Songs
					</a>
				</li>
			</ul>
		</div>

	</div>
</nav>

{% if all_albums %}
	<h3> All Albums Here: </h3>
	<ul>
		{% for album in all_albums %}
		<li>
			<a href="{% url 'blog:detail' album.id %}"> {{ album.album_title }} </a>
		</li>
		{% endfor %}
	</ul>

{% else %}
	<h2> You don't have any albums </h2>
{% endif%}